services:
  db:
    image: postgres:17.4
    restart: always
    environment:
      POSTGRES_USER: emclab
      POSTGRES_PASSWORD: emclab
      POSTGRES_DB: eshoplab
    volumes:
      - emc_lab_pgdata:/var/lib/postgresql/data
    ports:
      - "5434:5432"
volumes:
  emc_lab_pgdata:
