spring.datasource.url=jdbc:postgresql://localhost:5434/eshoplab
spring.datasource.username=emclab
spring.datasource.password=emclab

spring.jpa.hibernate.ddl-auto=validate

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
